# Site
name: 'X-TECH INNOVATIONS'
description: 'Xtension information Tech'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: '/mundana-theme-jekyll'
baseurl: '/'
disqus: ''
email: 'skps2000@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           sal
      # site:           https://www.wowthemes.net
      site:           https://skps2000.github.io/XTI_CORP/
      avatar:         /assets/images/avatar2.jpg
      bio:            "I am the Manager of XTI_CORP"
      email:          skps2000@gmail.com
      # twitter:        https://twitter.com/wowthemesnet
      twitter:        https://skps2000.github.io/XTI_CORP/

    manager:
      name:           Manager
      # site:           https://www.wowthemes.net
      site:           https://skps2000.github.io/XTI_CORP/
      avatar:         /assets/images/avatar1.jpg
      bio:            "I am the Manager of XTI_CORP"
      email:          skps2000@gmail.com
      # twitter:        https://twitter.com/wowthemesnet
      twitter:        https://skps2000.github.io/XTI_CORP/

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]